services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8001:8001"
    depends_on:
      - app-pagos
      - postgres
    restart: always 

  app-pagos:
    build: ./app-pagos
    container_name: app-pagos
    ports:
      - "8002:8002"
    env_file:
      - ./app-pagos/.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ventasdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: